# Generated by Django 3.0.6 on 2020-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200515_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'Declined')]),
        ),
    ]
