# Generated by Django 3.0.6 on 2020-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200515_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('declined', 'Declined')], max_length=20),
        ),
    ]
